### ISSUE TITLE
Update repo name

### ISSUE THREAD

**Issue by KFishner** [tasdikrahman/tf-module-gcp-network-subnet#1]
Hey there! Can you update your repo name to "terraform-google-network-subnet"? That's the official naming for Google modules which matches the naming of the [Terraform Google provider](https://www.terraform.io/docs/providers/google/index.html). 

That way your modules will show up with the verified Google modules when users search: https://registry.terraform.io/browse?provider=google

For reference here is how the repo name is used to create the module name in the TF Registry:
https://www.terraform.io/docs/registry/modules/publish.html

**Comment by tasdikrahman** [comment]
@KFishner I am facing issues re-adding this module via the registry. Gives a 

```bash
The same provider ("google") for this module already exists.
```

Would appreciate some help. Thanks

**Comment by banks** [comment]
Hi @tasdikrahman I think this is a known issue you are hitting which should be fixed soon. I'll update this issue when it is.

**Comment by tasdikrahman** [comment]
@banks Sure. That would be great. Thanks for the help.

**Comment by banks** [comment]
@tasdikrahman I've fixed the bug you hit now as far as I know.

As a bonus, I could push through the ingress of your module so you don't even have to re-submit :)

You can see it here: https://registry.terraform.io/modules/tasdikrahman/network-subnet/google/0.1.1

**Comment by banks** [comment]
I assume this issue can be closed now the preferred provider name is working.

**Comment by tasdikrahman** [comment]
@banks That's awesome. Thanks for the help guys :)
